### PR TITLE
backtrace: handle empty functions

### PR DESCRIPTION
**Pull request by kyrylo**
Fixes the build failure introduced by
https://circleci.com/gh/airbrake/airbrake-ruby/94

### CODE REVIEW

**Comment by zefer** [comment]
CI is failing, is this a work-in-progress?

**Comment by zefer** [comment]
Ah, Rubocop :cop: :smile:

**Comment by kyrylo** [comment]
Exactly. Rebuilding because https://github.com/airbrake/airbrake-ruby/pull/31 is merged :)

**Comment by kyrylo** [comment]
PTAL

**Comment by vmihailenco** [comment]
LGTM

**Pull request merged**
