### PR TITLE
notifier: delete deprecated {whitelist,blacklist}_keys methods

### LINKED ISSUE #123: Delete deprecated methods
It's about time to delete some [deprecated methods](https://github.com/airbrake/airbrake-ruby/blob/master/lib/airbrake-ruby.rb#L191-L207).

### PR DESCRIPTION
**Pull request by kyrylo**
Fixes #123 (Delete deprecated methods)

### CODE REVIEW

**Comment by shifi** [comment]
CI alert 🔴

**Comment by kyrylo** [comment]
Fixed CI. I have refactored old tests because they were relying on that old API (and removed 2 tests specific to those removed methods).

PTAL

**Comment by kyrylo** [comment]
This change will require a MINOR version bump, but I would like to postpone it because we've bumped it recently. I would like to get more fixes/features before merging this PR, so the bump is justified.

**Comment by shifi** [comment]
👍

**Pull request merged**
