### PR TITLE
#80 | Warn users that the project_key and project_id are blank

### PR DESCRIPTION
**Pull request by newdark**

### CODE REVIEW

**Comment by kyrylo** [comment]
Thanks for the PR. I think at the moment the best way to handle this would be checking the emptiness [here](https://github.com/airbrake/airbrake-ruby/blob/80bf59146a0b20856ef359908a9cd963d29fffef/lib/airbrake-ruby/notifier.rb#L33), so we could raise the same exception. Could you refactor your approach?

**Comment by newdark** [comment]
@kyrylo So the reason I was adding a warning and not a raise error is because in testing and development mode we don't care about those keys. I found that because of this I would work around the problem by calling to_s on the object so the system will not raise _both :project_id and :project_key are required_. It seams silly but not having to provide a project_id or project_key is a valid use case because there are some rails envs that don't require it. If you know a way to have it ignore the test and development environment when so it does not raise I think that might be the solution.

**Comment by kyrylo** [comment]
I'm aware that people find the raise behaviour a bit confusing and I'll probably change the way it works. However, I also think that this PR should not introduce diversion and work the same way as the check I linked to. By the way, to work around it, you could set `project_{id,key}` to a dummy value. 

In short, it's better to be consistent and a bit misleading, than inconsistent and misleading. Hope this makes sense.

**Comment by newdark** [comment]
I think you're right, this code was more as an example of a solution rather than actually solution to the problem. I am going to close this now and hopefully this will allow a better solution to be implemented. As I have no idea on what will work here or what the impact of changes could have on the tool. Anyway hope this helps.

**Comment by kyrylo** [comment]
Sounds good, thanks. Let's keep https://github.com/airbrake/airbrake-ruby/issues/80 open for now.

**Pull request closed without merging**
