### PR TITLE
notice: specify the language clearer in the context payload

### PR DESCRIPTION
**Pull request by kyrylo**

### CODE REVIEW

**Comment by vmihailenco** [comment]
Do we care about Ruby in JVM and other flavors? E.g. it could be JRuby/2.2.2

**Comment by kyrylo** [comment]
It's trivial to add support for this, so I don't see why not :)
Added & squashed commits.
PTAL

**Comment by vmihailenco** [comment]
Would be nice to have a test.

LGTM

**Comment by kyrylo** [comment]
The test wouldn't be trivial, because we run the test suite against many Rubies and its versions.

**Pull request merged**
