### PR TITLE
Support open_timeout and read_timeout

### PR DESCRIPTION
**Pull request by a2ikm**
Default values are Net::HTTP's.

### CODE REVIEW

**Comment by kyrylo** [comment]
Thanks for the PR, but why?

**Comment by a2ikm** [comment]
Two reasons:

1. Sometimes too many errors are invoked in our service. Then, we have to make sure that airbrake-gem don't wait long time.
1. We are using airbrake v4 in synchronous mode, and now moving to airbrake v5 in same mode. This is just our historical issue.

**Comment by kyrylo** [comment]
What do you think about having only one option - `timeout`. It would set the value for both `read_timeout` and `open_timeout`?

**Comment by kyrylo** [comment]
Gentle ping.

**Comment by crunis** [comment]
My 2 cents: I think joining both options in one makes sense, it simplifies the configuration while I can't think of a situation where one would really need to specify different values in this context.
What do you think @a2ikm ?

**Comment by a2ikm** [comment]
Yeah, I agree to join two options to one. It is simple and suits my purpose.

But I think it can wait for up to twice long time if setting same value to `read_timeout` and `open_timeout`.  How do you think? If it's OK, I'll fix my code.

**Comment by kyrylo** [comment]
Sounds good to me.

**Comment by crunis** [comment]
Increasing these values doesn't make the connection slower, it only makes slower to detect a timeout situation. If you are increasing them to cover an anomalously slow connection, in most situations you won't care what the value is as long as it covers the delay your experimenting.
So I'm also for joining them.

**Comment by kyrylo** [comment]
@a2ikm let me know if you don't have time to update the PR.

**Comment by a2ikm** [comment]
Sorry, I fixed the code.
Should I squash the commits?

**Comment by kyrylo** [comment]
Thanks! Yes, please squash. It would also be nice to fix the Rubocop failure.

**Comment by a2ikm** [comment]
I fixed Rubocop failure and squashed. Could you check that?

**Comment by kyrylo** [comment]
Looks great, thanks!

**Comment by a2ikm** [comment]
Thanks!

**Pull request merged**
